### PR TITLE
Add missing text, fix typos

### PR DESCRIPTION
**Pull request by vr8hub**
All compared against the scans.

Also, I'm curious why this, being a collection of short stories, is structured as chapters, with chapter semantics, chapter instead of story ids/filenames, etc.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! 

I don't remember re. stories. @robinwhittleton?

**Comment by robinwhittleton** [comment]
You could argue that they’re both chapters and short stories? It’s been a while since I produced it, but I remember them having a progression.

**Comment by acabal** [comment]
Yeah that sounds familiar. I'll put that in the production notes.

**Comment by vr8hub** [comment]
Well, no, *I* couldn’t argue that. :) The fact there’s some coherence to them doesn’t change the fact they’re short stories, were published as short stories, and *we* call it a collection of short stories. The definition of a short story (and our “article” epub type) is that they can standalone, and these can, and do.

But, NBD, so I’ll leave it with you two.

**Comment by robinwhittleton** [comment]
Do we support both chapter and se:short-story semantics on the same thing? :)

**Comment by acabal** [comment]
Why not? Something can be both. But short stories should almost always be in `<article>`. I guess the question is whether or not this is an actual short story collection where the stories could be syndicated individually without loss of narrative cohesion. I haven't read this so I don't know. If they can then this should probably be modeled as a regular short story compilation.

**Pull request merged**
