### PR TITLE
Transcription and printing corrections

### PR DESCRIPTION
**Pull request by tuskpot**
There are three changes in this pull request:
- Fix a simple transcription error (than -> that).
- Change to resolve an awkward phrase that I suspect to be an error in the original printing (then -> them).
- Relocate an awkward paragraph. On investigation, I think it was wholly moved by the printer from one page (where it makes sense) to the next page (where it doesn't). Page scans are [here](https://babel.hathitrust.org/cgi/pt?id=hvd.hwra7h&view=1up&seq=312).

I put the second two under a single editorial commit. Let me know if you have any questions or concerns about these.

### CODE REVIEW

**Comment by acabal** [comment]
I think the awkward phrase in chapter 9 could still be read like that correctly; we should not change it. For the relocated paragraph, we need to check the original French before we start doing things like rearranging paragraphs.

**Comment by tuskpot** [comment]
Fair points. I'll revise this pull request this to include only the actual transcription error, so that it can be corrected. For the other two issues, I'll see what the French edition looks like and maybe move this discussion to the mailing list.

**Comment by acabal** [comment]
OK great. If you can find the French it might be as easy as doing a quick Google Translate on those paragraphs. We don't need to be precise to get an idea if the paragraphs are in the right place or not.

**Comment by tuskpot** [comment]
I've removed the questionable changes from this pull request until I look up the original French. The only remaining change is strictly a transcription error from the source scans and should be okay to merge now.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
